<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\sprites\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>sprites\%(Filename)%(Extension)</Link>
    </None>
    <None Include="..\Audio\*.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>audio\%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

</Project>
